// This file is auto-generated by Class.js. Do not edit manually.

// Content from PostController.js
class PostController {
  constructor() {
    // PostController initialization logic
  }

  someMethod() {
    // Example method
  }
}

// Content from UserController.js
class UserController {
  constructor() {
    // UserController initialization logic
  }

  anotherMethod() {
    // Example method
  }
}

// AppController aggregates all controller instances
class AppController {
  constructor() {
    this.PostController = new PostController();
    this.UserController = new UserController();
  }
}

export default AppController;
